CREATE DATABASE IF NOT EXISTS plomarsa;

use plomarsa;

CREATE TABLE IF NOT EXISTS TAREA
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    titulo      VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL
);
